// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Persistence;

#nullable disable

namespace TaskManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519084148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("IX_Tasks_AssignedTo");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Tasks_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tasks_IsDeleted");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Tasks_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tasks_Status");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("IX_Tasks_Status_Priority");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 1",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Seed task #1"
                        },
                        new
                        {
                            Id = 2L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 2",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Seed task #2"
                        },
                        new
                        {
                            Id = 3L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 3",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Title = "Seed task #3"
                        },
                        new
                        {
                            Id = 4L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 4",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 1,
                            Title = "Seed task #4"
                        },
                        new
                        {
                            Id = 5L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 5",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 2,
                            Title = "Seed task #5"
                        },
                        new
                        {
                            Id = 6L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 6",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 0,
                            Title = "Seed task #6"
                        },
                        new
                        {
                            Id = 7L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 7",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Seed task #7"
                        },
                        new
                        {
                            Id = 8L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 8, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 8",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 8, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 2,
                            Title = "Seed task #8"
                        },
                        new
                        {
                            Id = 9L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 9, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 9",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 9, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed task #9"
                        },
                        new
                        {
                            Id = 10L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 10",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 10, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Seed task #10"
                        },
                        new
                        {
                            Id = 11L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 11, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 11",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 11, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 2,
                            Title = "Seed task #11"
                        },
                        new
                        {
                            Id = 12L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 12, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 12",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 12, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Seed task #12"
                        },
                        new
                        {
                            Id = 13L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 13, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 13",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 13, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Seed task #13"
                        },
                        new
                        {
                            Id = 14L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 14, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 14",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 14, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Seed task #14"
                        },
                        new
                        {
                            Id = 15L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 15",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 15, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Title = "Seed task #15"
                        },
                        new
                        {
                            Id = 16L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 16, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 16",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 16, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 1,
                            Title = "Seed task #16"
                        },
                        new
                        {
                            Id = 17L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 17, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 17",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 17, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 2,
                            Title = "Seed task #17"
                        },
                        new
                        {
                            Id = 18L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 18, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 18",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 18, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 0,
                            Title = "Seed task #18"
                        },
                        new
                        {
                            Id = 19L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 19, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 19",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 19, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Seed task #19"
                        },
                        new
                        {
                            Id = 20L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 20",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 20, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 2,
                            Title = "Seed task #20"
                        },
                        new
                        {
                            Id = 21L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 21, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 21",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 21, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed task #21"
                        },
                        new
                        {
                            Id = 22L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 22, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 22",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 22, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Seed task #22"
                        },
                        new
                        {
                            Id = 23L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 23, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 23",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 23, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 2,
                            Title = "Seed task #23"
                        },
                        new
                        {
                            Id = 24L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 24, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 24",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 24, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Seed task #24"
                        },
                        new
                        {
                            Id = 25L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 25",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 25, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Seed task #25"
                        },
                        new
                        {
                            Id = 26L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 26, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 26",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 26, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Seed task #26"
                        },
                        new
                        {
                            Id = 27L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 27, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 27",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 27, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Title = "Seed task #27"
                        },
                        new
                        {
                            Id = 28L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 28, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 28",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 28, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 1,
                            Title = "Seed task #28"
                        },
                        new
                        {
                            Id = 29L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 29, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 29",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 29, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 2,
                            Title = "Seed task #29"
                        },
                        new
                        {
                            Id = 30L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 30",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 30, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 0,
                            Title = "Seed task #30"
                        },
                        new
                        {
                            Id = 31L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 31, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 31",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 31, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Seed task #31"
                        },
                        new
                        {
                            Id = 32L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 32, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 32",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 32, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 2,
                            Title = "Seed task #32"
                        },
                        new
                        {
                            Id = 33L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 33, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 33",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 33, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed task #33"
                        },
                        new
                        {
                            Id = 34L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 34, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 34",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 34, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Seed task #34"
                        },
                        new
                        {
                            Id = 35L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 35, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 35",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 35, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 2,
                            Title = "Seed task #35"
                        },
                        new
                        {
                            Id = 36L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 36, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 36",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 36, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Seed task #36"
                        },
                        new
                        {
                            Id = 37L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 37, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 37",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 37, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Seed task #37"
                        },
                        new
                        {
                            Id = 38L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 38, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 38",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 38, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Seed task #38"
                        },
                        new
                        {
                            Id = 39L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 39, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 39",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 39, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Title = "Seed task #39"
                        },
                        new
                        {
                            Id = 40L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 40, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 40",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 40, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 1,
                            Title = "Seed task #40"
                        },
                        new
                        {
                            Id = 41L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 41, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 41",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 41, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 2,
                            Title = "Seed task #41"
                        },
                        new
                        {
                            Id = 42L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 42, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 42",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 42, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 0,
                            Title = "Seed task #42"
                        },
                        new
                        {
                            Id = 43L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 43, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 43",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 43, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Seed task #43"
                        },
                        new
                        {
                            Id = 44L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 44, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 44",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 44, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 2,
                            Title = "Seed task #44"
                        },
                        new
                        {
                            Id = 45L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 45",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 45, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed task #45"
                        },
                        new
                        {
                            Id = 46L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 46, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 46",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 46, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Seed task #46"
                        },
                        new
                        {
                            Id = 47L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 47, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 47",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 47, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 2,
                            Title = "Seed task #47"
                        },
                        new
                        {
                            Id = 48L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 48, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 48",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 48, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Seed task #48"
                        },
                        new
                        {
                            Id = 49L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 49",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 49, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Seed task #49"
                        },
                        new
                        {
                            Id = 50L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 50, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 50",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 50, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Seed task #50"
                        },
                        new
                        {
                            Id = 51L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 51, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 51",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 51, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Title = "Seed task #51"
                        },
                        new
                        {
                            Id = 52L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 52, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 52",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 52, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 1,
                            Title = "Seed task #52"
                        },
                        new
                        {
                            Id = 53L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 53, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 53",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 53, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 2,
                            Title = "Seed task #53"
                        },
                        new
                        {
                            Id = 54L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 54, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 54",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 54, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 0,
                            Title = "Seed task #54"
                        },
                        new
                        {
                            Id = 55L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 55, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 55",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 55, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Seed task #55"
                        },
                        new
                        {
                            Id = 56L,
                            AssignedTo = "bob",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 56",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 56, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 2,
                            Title = "Seed task #56"
                        },
                        new
                        {
                            Id = 57L,
                            AssignedTo = "carol",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 57, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 57",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 57, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed task #57"
                        },
                        new
                        {
                            Id = 58L,
                            AssignedTo = "dave",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 58, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 58",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 58, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Seed task #58"
                        },
                        new
                        {
                            Id = 59L,
                            AssignedTo = "erin",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 59, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 59",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 59, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 2,
                            Title = "Seed task #59"
                        },
                        new
                        {
                            Id = 60L,
                            AssignedTo = "alice",
                            CreatedDate = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-generated seed task number 60",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Seed task #60"
                        });
                });

            modelBuilder.Entity("TaskManagement.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
